netty:
#  port: 1433
  port: 1715
  boss-count: 1    # Netty boss 쓰레드 개수
  worker-count: 4  # Netty worker 쓰레드 개수
  keep-alive: true # TCP keep-alive 설정
  backlog: 100     # TCP backlog 설정

logging:
  level:
    root: INFO
    com.example.daq_monitoring_sw: DEBUG # 애플리케이션 패키지 로그 레벨 설정
    org.springframework: INFO # Spring 관련 로그 레벨 설정


spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/daqcenter?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dactech
    password: 9531
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: validate
    open-in-view: true
    show_sql: false

server:
  port: 9531